apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
  namespace: arc-k8
spec:
  selector:
      matchLabels:
        app: web2
  replicas: 1
  template:
      metadata:
        labels:
            app: web2
      spec:
        containers:
        - name: web2
          image:  khanasif1/azure_arc_k8_web:rc1.0
          imagePullPolicy: Always         
          readinessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          livenessProbe:
            httpGet:
              port: 80
              path: /healthcheck
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: message
            value: V:0 K8s - Welcome to Azure Arc GitOps            
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service2
  namespace: arc-k8
spec:
  selector:
    app: web2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP      