apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: arc-k8-org
spec:
  rules:
  - http:
      paths:  
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80                                                  