apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: arc-k8-org
spec:
  rules:
  - http:
      paths:  
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80                                                  